"""Generate/update Spotify playlists from labels. Idempotent (matched by name)."""
from __future__ import annotations

import json

import spotipy

import config
import db


def _clusters() -> dict[str, list[str]]:
    """Build {playlist_name: [track_ids]} for every enabled scheme."""
    out: dict[str, list[str]] = {}
    with db.connect() as conn:
        rows = conn.execute(
            "SELECT track_id, genre_buckets, subgenres, vibes FROM labels"
        ).fetchall()

    for r in rows:
        tid = r["track_id"]
        genres = json.loads(r["genre_buckets"] or "[]")
        subgenres = json.loads(r["subgenres"] or "[]")
        vibes = json.loads(r["vibes"] or "[]")
        if "genre" in config.PLAYLIST_SCHEMES:
            for g in genres:
                out.setdefault(f"{g}", []).append(tid)
        if "subgenre" in config.PLAYLIST_SCHEMES:
            # precise subgenre playlists; fall back to the coarse genre so a
            # track with no subgenre still lands somewhere
            for sg in (subgenres or genres):
                out.setdefault(f"{sg}", []).append(tid)
        if "vibe" in config.PLAYLIST_SCHEMES:
            for v in vibes:
                out.setdefault(f"{v}", []).append(tid)
        if "combined" in config.PLAYLIST_SCHEMES:
            for g in genres:
                for v in vibes:
                    out.setdefault(f"{v} {g}", []).append(tid)

    # drop tiny clusters
    return {
        name: ids
        for name, ids in out.items()
        if len(ids) >= config.MIN_TRACKS_PER_PLAYLIST
    }


def _existing_playlists(sp: spotipy.Spotify, user_id: str) -> dict[str, str]:
    """Map prefixed playlist name -> id, for playlists we manage."""
    found: dict[str, str] = {}
    results = sp.current_user_playlists(limit=50)
    while results:
        for p in results["items"]:
            if p["owner"]["id"] == user_id and p["name"].startswith(config.PLAYLIST_PREFIX):
                found[p["name"]] = p["id"]
        results = sp.next(results) if results.get("next") else None
    return found


def _replace_tracks(sp: spotipy.Spotify, playlist_id: str, track_ids: list[str]) -> None:
    uris = [f"spotify:track:{t}" for t in track_ids]
    sp.playlist_replace_items(playlist_id, uris[:100])
    for i in range(100, len(uris), 100):
        sp.playlist_add_items(playlist_id, uris[i : i + 100])


def create_named_playlist(sp: spotipy.Spotify, name: str, track_ids: list[str]) -> str:
    """Create or update a single prefixed playlist with the given tracks.

    Idempotent (matched by prefixed name), like sync_playlists. Returns the
    full playlist name used. Powers the GUI "Create playlist" button.
    """
    user_id = sp.current_user()["id"]
    full = name if name.startswith(config.PLAYLIST_PREFIX) else f"{config.PLAYLIST_PREFIX}{name}"
    pid = _existing_playlists(sp, user_id).get(full)
    if pid is None:
        pl = sp.user_playlist_create(
            user_id, full, public=config.PLAYLIST_VISIBILITY_PUBLIC,
            description="Auto-generated by Spotify_Automation",
        )
        pid = pl["id"]
    _replace_tracks(sp, pid, track_ids)
    return full


def sync_playlists(sp: spotipy.Spotify, dry_run: bool = False) -> list[tuple[str, int]]:
    user_id = sp.current_user()["id"]
    clusters = _clusters()
    summary: list[tuple[str, int]] = []
    if dry_run:
        return sorted(((n, len(ids)) for n, ids in clusters.items()), key=lambda x: -x[1])

    existing = _existing_playlists(sp, user_id)
    for name, track_ids in clusters.items():
        full = f"{config.PLAYLIST_PREFIX}{name}"
        pid = existing.get(full)
        if pid is None:
            pl = sp.user_playlist_create(
                user_id, full, public=config.PLAYLIST_VISIBILITY_PUBLIC,
                description="Auto-generated by Spotify_Automation",
            )
            pid = pl["id"]
        _replace_tracks(sp, pid, track_ids)
        summary.append((full, len(track_ids)))
    return sorted(summary, key=lambda x: -x[1])
