"""Generate/update Spotify playlists from labels. Idempotent (matched by name)."""
from __future__ import annotations

import json
import logging

import spotipy

import config
import db

log = logging.getLogger(__name__)
_ASCII_SAFE_PLAYLIST_PREFIX = "VibeThePlaylist - "
_REAUTH_MESSAGE = "Spotify rejected your login. Log out, sign back in, and try again."
_SCOPE_MESSAGE = "Spotify did not grant playlist-edit access. Log out, sign back in, and approve playlist permissions."
_TOKEN_ERROR_MARKERS = ("invalid token", "expired token", "token rejected", "access token")
_PERMISSION_ERROR_MARKERS = ("insufficient scope", "missing scope", "missing permission")


class PlaylistError(RuntimeError):
    """User-safe error raised when Spotify playlist operations fail."""

    def __init__(self, user_message: str):
        super().__init__(user_message)
        self.user_message = user_message


def _strip_managed_prefix(name: str) -> str:
    for prefix in (config.PLAYLIST_PREFIX, _ASCII_SAFE_PLAYLIST_PREFIX):
        if name.startswith(prefix):
            return name[len(prefix) :]
    return name


def _is_managed_playlist_name(name: str) -> bool:
    return name.startswith(config.PLAYLIST_PREFIX) or name.startswith(_ASCII_SAFE_PLAYLIST_PREFIX)


def _managed_playlist_names(name: str) -> list[str]:
    base = _strip_managed_prefix(name).strip()
    primary = f"{config.PLAYLIST_PREFIX}{base}"
    fallback = f"{_ASCII_SAFE_PLAYLIST_PREFIX}{base}"
    return [primary] if primary == fallback or primary.isascii() else [primary, fallback]


def _spotify_error_detail(exc: spotipy.SpotifyException) -> str:
    parts: list[str] = []
    if isinstance(exc.msg, dict):
        # Prefer Spotify's most user-relevant message field in priority order.
        for key in ("error_description", "error", "message"):
            value = exc.msg.get(key)
            if value:
                parts.append(str(value))
                break
    elif exc.msg:
        parts.append(str(exc.msg))
    if exc.reason:
        parts.append(str(exc.reason))
    return " ".join(parts).strip()


def _is_permission_error(exc: spotipy.SpotifyException, detail_lc: str) -> bool:
    code = str(getattr(exc, "code", "") or "")
    return (
        exc.http_status == 403
        or code == "insufficient_scope"
        or any(marker in detail_lc for marker in _PERMISSION_ERROR_MARKERS)
    )


def _is_invalid_request(exc: spotipy.SpotifyException) -> bool:
    return exc.http_status == 400 or str(getattr(exc, "code", "") or "") == "invalid_request"


def _playlist_error_message(exc: spotipy.SpotifyException) -> str:
    detail_lc = _spotify_error_detail(exc).lower()
    if exc.http_status == 429:
        if isinstance(exc.headers, dict):
            wait = exc.headers.get("Retry-After")
            if wait:
                return f"Spotify is rate-limiting playlist changes. Wait about {wait} seconds, then try again."
        return "Spotify is rate-limiting playlist changes. Please wait a bit, then try again."
    if exc.http_status == 401 or any(marker in detail_lc for marker in _TOKEN_ERROR_MARKERS):
        return _REAUTH_MESSAGE
    if _is_permission_error(exc, detail_lc):
        return _SCOPE_MESSAGE
    if _is_invalid_request(exc):
        return "Spotify rejected the playlist request. Try a shorter playlist name using letters, numbers, and spaces only."
    return "Spotify could not save the playlist right now. Please try again."


def _should_retry_with_ascii_name(exc: spotipy.SpotifyException, name: str, fallback: str) -> bool:
    return (
        fallback != name
        and fallback.isascii()
        and not name.isascii()
        and _is_invalid_request(exc)
    )


def _create_playlist(
    sp: spotipy.Spotify, user_id: str, name: str, fallback_name: str
) -> tuple[str, str]:
    try:
        pl = sp.user_playlist_create(
            user_id,
            name,
            public=config.PLAYLIST_VISIBILITY_PUBLIC,
            description="Auto-generated by Spotify_Automation",
        )
        return pl["id"], name
    except spotipy.SpotifyException as exc:
        if _should_retry_with_ascii_name(exc, name, fallback_name):
            log.info(
                "Spotify rejected playlist name %r; retrying with ASCII-safe name %r",
                name,
                fallback_name,
            )
            pl = sp.user_playlist_create(
                user_id,
                fallback_name,
                public=config.PLAYLIST_VISIBILITY_PUBLIC,
                description="Auto-generated by Spotify_Automation",
            )
            return pl["id"], fallback_name
        raise


def _ensure_playlist(
    sp: spotipy.Spotify, existing: dict[str, str], user_id: str, name: str
) -> tuple[str, str]:
    names = _managed_playlist_names(name)
    for candidate in names:
        pid = existing.get(candidate)
        if pid is not None:
            return pid, candidate
    pid, chosen_name = _create_playlist(sp, user_id, names[0], names[-1])
    existing[chosen_name] = pid
    return pid, chosen_name


def _clusters() -> dict[str, list[str]]:
    """Build {playlist_name: [track_ids]} for every enabled scheme."""
    out: dict[str, list[str]] = {}
    with db.connect() as conn:
        rows = conn.execute(
            "SELECT track_id, genre_buckets, subgenres, vibes FROM labels"
        ).fetchall()

    for r in rows:
        tid = r["track_id"]
        genres = json.loads(r["genre_buckets"] or "[]")
        subgenres = json.loads(r["subgenres"] or "[]")
        vibes = json.loads(r["vibes"] or "[]")
        if "genre" in config.PLAYLIST_SCHEMES:
            for g in genres:
                out.setdefault(f"{g}", []).append(tid)
        if "subgenre" in config.PLAYLIST_SCHEMES:
            # precise subgenre playlists; fall back to the coarse genre so a
            # track with no subgenre still lands somewhere
            for sg in (subgenres or genres):
                out.setdefault(f"{sg}", []).append(tid)
        if "vibe" in config.PLAYLIST_SCHEMES:
            for v in vibes:
                out.setdefault(f"{v}", []).append(tid)
        if "combined" in config.PLAYLIST_SCHEMES:
            for g in genres:
                for v in vibes:
                    out.setdefault(f"{v} {g}", []).append(tid)

    # drop tiny clusters
    return {
        name: ids
        for name, ids in out.items()
        if len(ids) >= config.MIN_TRACKS_PER_PLAYLIST
    }


def _existing_playlists(sp: spotipy.Spotify, user_id: str) -> dict[str, str]:
    """Map prefixed playlist name -> id, for playlists we manage."""
    found: dict[str, str] = {}
    results = sp.current_user_playlists(limit=50)
    while results:
        for p in results["items"]:
            if p["owner"]["id"] == user_id and _is_managed_playlist_name(p["name"]):
                found[p["name"]] = p["id"]
        results = sp.next(results) if results.get("next") else None
    return found


def _replace_tracks(sp: spotipy.Spotify, playlist_id: str, track_ids: list[str]) -> None:
    uris = [f"spotify:track:{t}" for t in track_ids]
    sp.playlist_replace_items(playlist_id, uris[:100])
    for i in range(100, len(uris), 100):
        sp.playlist_add_items(playlist_id, uris[i : i + 100])


def create_named_playlist(sp: spotipy.Spotify, name: str, track_ids: list[str]) -> str:
    """Create or update a single prefixed playlist with the given tracks.

    Idempotent (matched by prefixed name), like sync_playlists. Returns the
    full playlist name used. Powers the GUI "Create playlist" button.
    """
    try:
        user_id = sp.current_user()["id"]
        existing = _existing_playlists(sp, user_id)
        pid, full = _ensure_playlist(sp, existing, user_id, name)
        _replace_tracks(sp, pid, track_ids)
        return full
    except spotipy.SpotifyException as exc:
        log.exception("Failed to create or update playlist %r", name)
        raise PlaylistError(_playlist_error_message(exc)) from exc


def sync_playlists(sp: spotipy.Spotify, dry_run: bool = False) -> list[tuple[str, int]]:
    user_id = sp.current_user()["id"]
    clusters = _clusters()
    summary: list[tuple[str, int]] = []
    if dry_run:
        return sorted(((n, len(ids)) for n, ids in clusters.items()), key=lambda x: -x[1])

    existing = _existing_playlists(sp, user_id)
    for name, track_ids in clusters.items():
        try:
            pid, full = _ensure_playlist(sp, existing, user_id, name)
            _replace_tracks(sp, pid, track_ids)
            summary.append((full, len(track_ids)))
        except spotipy.SpotifyException as exc:
            log.exception("Failed to sync playlist %r", name)
            raise PlaylistError(_playlist_error_message(exc)) from exc
    return sorted(summary, key=lambda x: -x[1])
