"""Auto-generated subgenre taxonomy — merged into config.SUBGENRE_BUCKETS.

DO NOT hand-tune this file as your primary surface: it is (re)written by
`python cli.py gen-subgenres`, which calls Claude with web search to fetch an
exhaustive subgenre list whenever a new coarse genre is added to
`config.GENRE_BUCKETS`. Hand-curated entries in `config.SUBGENRE_BUCKETS` take
precedence over anything here (see `config._merge_subgenres`).

Shape mirrors config.SUBGENRE_BUCKETS:
    coarse bucket -> {subgenre label: [lowercase needle substrings]}

This initial set was researched from public genre references; regenerate or
extend it with the CLI rather than editing by hand.
"""
from __future__ import annotations

GENERATED_SUBGENRES: dict[str, dict[str, list[str]]] = {
    "Hip-hop/Rap": {
        "Trap": ["trap"],
        "Drill": ["drill"],
        "Boom Bap": ["boom bap"],
        "Cloud Rap": ["cloud rap"],
        "Conscious Hip Hop": ["conscious hip hop", "conscious rap"],
        "Gangsta Rap": ["gangsta rap", "gangsta"],
        "G-Funk": ["g-funk", "g funk"],
        "Grime": ["grime"],
        "Crunk": ["crunk"],
        "Phonk": ["phonk"],
        "Mumble Rap": ["mumble rap"],
        "Emo Rap": ["emo rap"],
        "Jazz Rap": ["jazz rap"],
        "Alternative Hip Hop": ["alternative hip hop", "alternative rap"],
        "Hardcore Hip Hop": ["hardcore hip hop"],
        "Old School Hip Hop": ["old school hip hop", "old school rap"],
        "Southern Hip Hop": ["southern hip hop", "dirty south"],
        "East Coast Hip Hop": ["east coast hip hop", "east coast rap"],
        "West Coast Hip Hop": ["west coast hip hop", "west coast rap"],
        "UK Hip Hop": ["uk hip hop", "british hip hop"],
        "Memphis Rap": ["memphis rap"],
        "Horrorcore": ["horrorcore"],
        "Pop Rap": ["pop rap"],
    },
    "R&B/Soul": {
        "Neo Soul": ["neo soul", "neo-soul"],
        "Contemporary R&B": ["contemporary r&b", "contemporary rnb"],
        "Funk": ["funk"],
        "Motown": ["motown"],
        "Quiet Storm": ["quiet storm"],
        "New Jack Swing": ["new jack swing"],
        "Northern Soul": ["northern soul"],
        "Southern Soul": ["southern soul"],
        "Gospel": ["gospel"],
        "Disco": ["disco"],
        "Alternative R&B": ["alternative r&b", "alternative rnb", "pbr&b"],
    },
    "Electronic": {
        "House": ["house"],
        "Deep House": ["deep house"],
        "Tech House": ["tech house"],
        "Progressive House": ["progressive house"],
        "Acid House": ["acid house"],
        "Afro House": ["afro house"],
        "Techno": ["techno"],
        "Detroit Techno": ["detroit techno"],
        "Minimal Techno": ["minimal techno", "minimal"],
        "Trance": ["trance"],
        "Psytrance": ["psytrance", "psychedelic trance"],
        "Drum & Bass": ["drum and bass", "dnb", "drum n bass"],
        "Liquid DnB": ["liquid funk", "liquid dnb"],
        "Neurofunk": ["neurofunk"],
        "Jungle": ["jungle"],
        "Dubstep": ["dubstep"],
        "Brostep": ["brostep"],
        "Future Bass": ["future bass"],
        "Electro": ["electro"],
        "Big Room": ["big room"],
        "Garage": ["garage"],
        "UK Garage": ["uk garage", "2-step"],
        "Synthwave": ["synthwave"],
        "Hardstyle": ["hardstyle"],
        "Gabber": ["gabber"],
        "Breakbeat": ["breakbeat", "breaks"],
        "IDM": ["idm", "intelligent dance"],
        "Downtempo": ["downtempo"],
        "Trip Hop": ["trip hop", "trip-hop"],
        "Nu-Disco": ["nu-disco", "nu disco"],
    },
    "Pop": {
        "Synthpop": ["synthpop", "synth-pop"],
        "Indie Pop": ["indie pop"],
        "Dance Pop": ["dance pop"],
        "K-pop": ["k-pop", "kpop"],
        "J-pop": ["j-pop", "jpop"],
        "Electropop": ["electropop"],
        "Dream Pop": ["dream pop"],
        "Art Pop": ["art pop"],
        "Power Pop": ["power pop"],
        "Teen Pop": ["teen pop"],
        "Hyperpop": ["hyperpop"],
        "Bubblegum Pop": ["bubblegum"],
        "Bedroom Pop": ["bedroom pop"],
        "Baroque Pop": ["baroque pop"],
        "Pop Rock": ["pop rock"],
    },
    "Rock": {
        "Classic Rock": ["classic rock"],
        "Alternative Rock": ["alternative rock", "alternative"],
        "Indie Rock": ["indie rock"],
        "Punk Rock": ["punk"],
        "Pop Punk": ["pop punk"],
        "Hard Rock": ["hard rock"],
        "Grunge": ["grunge"],
        "Psychedelic Rock": ["psychedelic rock", "psych rock"],
        "Progressive Rock": ["progressive rock", "prog rock"],
        "Garage Rock": ["garage rock"],
        "Post-Punk": ["post-punk", "post punk"],
        "Post-Rock": ["post-rock", "post rock"],
        "Shoegaze": ["shoegaze"],
        "Surf Rock": ["surf rock", "surf"],
        "Glam Rock": ["glam rock", "glam"],
        "Math Rock": ["math rock"],
        "Emo": ["emo"],
        "Southern Rock": ["southern rock"],
        "Folk Rock": ["folk rock"],
        "Blues Rock": ["blues rock"],
        "New Wave": ["new wave"],
    },
    "Metal": {
        "Heavy Metal": ["heavy metal"],
        "Thrash Metal": ["thrash"],
        "Death Metal": ["death metal"],
        "Melodic Death Metal": ["melodic death", "melodeath"],
        "Technical Death Metal": ["technical death", "tech death"],
        "Black Metal": ["black metal"],
        "Doom Metal": ["doom"],
        "Power Metal": ["power metal"],
        "Metalcore": ["metalcore"],
        "Deathcore": ["deathcore"],
        "Nu Metal": ["nu metal", "nu-metal"],
        "Groove Metal": ["groove metal"],
        "Progressive Metal": ["progressive metal", "prog metal"],
        "Djent": ["djent"],
        "Symphonic Metal": ["symphonic metal"],
        "Folk Metal": ["folk metal"],
        "Industrial Metal": ["industrial metal"],
        "Sludge Metal": ["sludge"],
        "Speed Metal": ["speed metal"],
        "Grindcore": ["grindcore"],
        "Gothic Metal": ["gothic metal"],
    },
    "Jazz": {
        "Bebop": ["bebop"],
        "Swing": ["swing"],
        "Big Band": ["big band"],
        "Cool Jazz": ["cool jazz"],
        "Hard Bop": ["hard bop"],
        "Free Jazz": ["free jazz"],
        "Jazz Fusion": ["fusion", "jazz fusion"],
        "Smooth Jazz": ["smooth jazz"],
        "Modal Jazz": ["modal jazz"],
        "Latin Jazz": ["latin jazz"],
        "Bossa Nova": ["bossa nova"],
        "Afro-Cuban Jazz": ["afro-cuban jazz", "afro cuban jazz"],
        "Gypsy Jazz": ["gypsy jazz"],
        "Dixieland": ["dixieland"],
        "Acid Jazz": ["acid jazz"],
        "Soul Jazz": ["soul jazz"],
        "Vocal Jazz": ["vocal jazz"],
    },
    "Classical": {
        "Baroque": ["baroque"],
        "Classical Period": ["classical period"],
        "Romantic": ["romantic", "romanticism"],
        "Opera": ["opera"],
        "Orchestral": ["orchestra", "orchestral"],
        "Chamber Music": ["chamber"],
        "Piano": ["piano"],
        "Choral": ["choral", "choir"],
        "Symphony": ["symphony", "symphonic"],
        "Concerto": ["concerto"],
        "Minimalism": ["minimalism", "minimalist"],
        "Contemporary Classical": ["contemporary classical", "modern classical"],
        "Early Music": ["early music", "medieval", "renaissance"],
        "Neoclassical": ["neoclassical"],
    },
    "Folk/Acoustic": {
        "Singer-Songwriter": ["singer-songwriter", "singer songwriter"],
        "Americana": ["americana"],
        "Country": ["country"],
        "Bluegrass": ["bluegrass"],
        "Indie Folk": ["indie folk"],
        "Folk Rock": ["folk rock"],
        "Contemporary Folk": ["contemporary folk"],
        "Traditional Folk": ["traditional folk", "folk music"],
        "Celtic": ["celtic"],
        "Alt-Country": ["alt-country", "alt country"],
        "Outlaw Country": ["outlaw country"],
        "Country Rock": ["country rock"],
        "Folk Pop": ["folk pop"],
        "Old-Time": ["old-time", "old time"],
    },
    "Latin": {
        "Reggaeton": ["reggaeton"],
        "Salsa": ["salsa"],
        "Bachata": ["bachata"],
        "Cumbia": ["cumbia"],
        "Latin Pop": ["latin pop"],
        "Latin Trap": ["latin trap", "trap latino"],
        "Merengue": ["merengue"],
        "Bossa Nova": ["bossa nova"],
        "Samba": ["samba"],
        "Tango": ["tango"],
        "Mariachi": ["mariachi"],
        "Ranchera": ["ranchera"],
        "Banda": ["banda"],
        "Regional Mexican": ["regional mexican", "corrido"],
        "Timba": ["timba"],
        "Bolero": ["bolero"],
        "Vallenato": ["vallenato"],
        "Dembow": ["dembow"],
        "Mambo": ["mambo"],
        "Latin Rock": ["latin rock", "rock en espanol"],
    },
    "Reggae/Dub": {
        "Roots Reggae": ["roots reggae", "roots"],
        "Dancehall": ["dancehall"],
        "Ska": ["ska"],
        "Dub": ["dub"],
        "Rocksteady": ["rocksteady"],
        "Ragga": ["ragga"],
        "Lovers Rock": ["lovers rock"],
        "Reggae Fusion": ["reggae fusion"],
    },
    "Ambient/Lo-fi": {
        "Lo-fi": ["lo-fi", "lofi"],
        "Lofi Hip Hop": ["lofi hip hop", "lo-fi hip hop"],
        "Chillhop": ["chillhop"],
        "Downtempo": ["downtempo"],
        "Ambient": ["ambient"],
        "Drone": ["drone"],
        "Dark Ambient": ["dark ambient"],
        "Chillwave": ["chillwave"],
        "Trip Hop": ["trip hop", "trip-hop"],
        "New Age": ["new age"],
        "Vaporwave": ["vaporwave"],
        "Instrumental Hip Hop": ["instrumental hip hop"],
    },
}
