"""Interactive .env setup. Run once to create/update your .env file.

    conda activate Spotify
    python setup_env.py

Press Enter to keep an existing value (shown in brackets) or skip an optional key.
"""
from __future__ import annotations

from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent / ".env"

# (key, prompt, default, required)
FIELDS = [
    ("SPOTIFY_CLIENT_ID", "Spotify Client ID", "", True),
    ("SPOTIFY_CLIENT_SECRET", "Spotify Client Secret", "", True),
    ("SPOTIFY_REDIRECT_URI", "Spotify Redirect URI", "http://127.0.0.1:8888/callback", True),
    ("LASTFM_API_KEY", "Last.fm API key", "", True),
    ("ANTHROPIC_API_KEY", "Anthropic API key (optional, only for LLM)", "", False),
]


def read_existing() -> dict[str, str]:
    values: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                values[k.strip()] = v.strip()
    return values


def main() -> None:
    existing = read_existing()
    print(f"Writing to {ENV_PATH}\n")
    values: dict[str, str] = {}

    for key, label, default, required in FIELDS:
        current = existing.get(key) or default
        shown = current if current else "empty"
        while True:
            entered = input(f"{label} [{shown}]: ").strip()
            value = entered or current
            if required and not value:
                print("  -> required, please enter a value.")
                continue
            values[key] = value
            break

    lines = [
        "# Generated by setup_env.py — do not commit this file.",
        *(f"{k}={values.get(k, '')}" for k, _, _, _ in FIELDS),
        "",
    ]
    ENV_PATH.write_text("\n".join(lines))
    try:
        ENV_PATH.chmod(0o600)  # keep secrets private
    except OSError:
        pass

    missing = [k for k, _, _, req in FIELDS if req and not values.get(k)]
    print(f"\n✓ Wrote {ENV_PATH}")
    if missing:
        print(f"⚠ Still missing required keys: {', '.join(missing)}")
    else:
        print("All required keys set. Next: python cli.py all")


if __name__ == "__main__":
    main()
